location_gates = {
    "WOR Access" : [
        "Floating Cont. Arrive",
        "Floating Cont. Beast",
        "Floating Cont. Escape",
        "Magitek Factory Trash",
        "Magitek Factory Guard",
        "Magitek Factory Finish",
        "Narshe Battle",
    ],
    "Character or Esper WOB" : [
        "Burning House",
        "Lete River",
        "Mt. Kolts",
        "Narshe Moogle Defense",
        "Opera House Disruption",
        "Phantom Train",
        "Veldt",
        "Zozo Tower",
    ],
    "Character or Esper WOR" : [
        "Ancient Castle",
        "Doma Dream Awaken",
        "Fanatic's Tower Follower",
        "Mobliz Attack",
        "Owzer's Mansion",
        "Phoenix Cave",
        "Umaro's Cave",
        "Zone Eater",
    ],
    "Esper or Item WOB" : [
        "Auction 1",
        "Auction 2",
        "Baren Falls",
        "Doma Siege",
        "Esper Mountain",
        "Imperial Camp",
        "Lone Wolf Chase",
        "Serpent Trench",
        "South Figaro Cave",
        "Tzen Thief",
        "Whelk Gate",
    ],
    "Esper or Item WOR" : [
        "Auction 1",
        "Auction 2",
        "Collapsing House",
        "Doma Dream Door",
        "Doma Dream Throne",
        "Daryl's Tomb",
        "Ebot's Rock",
        "Figaro Castle Engine",
        "Figaro Castle Throne",
        "Kohlingen Cafe",
        "Mt. Zozo",
        "Narshe Weapon Shop",
        "Search The Skies",
        "Tritoch Cliff",
        "Tzen Thief",
        "Veldt Cave",
    ],
    "Item Only WOB": [
        "Gau's Father's House",
        "Narshe Weapon Shop Mines",
        "Sealed Gate",
        "South Figaro Prisoner",
    ],
    "Item Only WOR": [
        "Ancient Castle Dragon",
        "Fanatic's Tower Dragon",
        "Fanatic's Tower Leader",
        "Kefka's Tower Cell Beast",
        "Kefka's Tower Dragon G",
        "Kefka's Tower Dragon S",
        "Lone Wolf Moogle Room",
        "Mt. Zozo Dragon",
        "Narshe Dragon",
        "Opera House Dragon",
        "Phoenix Cave Dragon",
    ],
}